import {
  GALLERY_ALIGNMENT,
  GALLERY_COLOR_VARIANT,
} from '../Gallery/Gallery.constants';

export const EVENTS_PAGE_ALIGNMENT = GALLERY_ALIGNMENT;

export const EVENTS_PAGE_TITLE_COLOR_VARIANT = GALLERY_COLOR_VARIANT;
