import {
  TYPOGRAPHY_ALIGNMENT,
  TYPOGRAPHY_COLORS,
} from '../Typography/Typography.constants';

export const GALLERY_COLOR_VARIANT = {
  TEXT: 'biały',
  ACCENT: 'akcent (fioletowy)',
  GRADIENT_LEFT: 'gradient (z lewej do prawej)',
  GRADIENT_RIGHT: 'gradient (z prawej do lewej)',
} as const;

export const GALLERY_ALIGNMENT = {
  START: 'po lewej',
  CENTER: 'środek',
  END: 'po prawej',
} as const;

export const TYPOGRAPHY_ALIGNMENT_FROM_GALLERY = {
  [GALLERY_ALIGNMENT.START]: TYPOGRAPHY_ALIGNMENT.START,
  [GALLERY_ALIGNMENT.CENTER]: TYPOGRAPHY_ALIGNMENT.CENTER,
  [GALLERY_ALIGNMENT.END]: TYPOGRAPHY_ALIGNMENT.END,
} as const;

export const GALLERY_ALIGNMENT_FROM_API = {
  [GALLERY_ALIGNMENT.START]: '',
  [GALLERY_ALIGNMENT.CENTER]: 'gallery_centerAlignment',
  [GALLERY_ALIGNMENT.END]: 'gallery_endAlignment',
} as const;

export const GALLERY_TYPOGRAPHY_COLOR_FROM_API = {
  [GALLERY_COLOR_VARIANT.TEXT]: TYPOGRAPHY_COLORS.TEXT,
  [GALLERY_COLOR_VARIANT.ACCENT]: TYPOGRAPHY_COLORS.ACCENT,
  [GALLERY_COLOR_VARIANT.GRADIENT_LEFT]: TYPOGRAPHY_COLORS.GRADIENT_LEFT,
  [GALLERY_COLOR_VARIANT.GRADIENT_RIGHT]: TYPOGRAPHY_COLORS.GRADIENT_RIGHT,
};
